---

- name: download base16-shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ home }}/.config/base16-shell"

- name: setup base16 in bashrc
  blockinfile:
    marker: "# {mark} Base16 Configuration"
    block: | 
      BASE16_SHELL=$HOME/.config/base16-shell/
      [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
      alias recolor='RAND_ENV=`alias -p | grep -Eo "(_base16 ".*" [a-z\-]*)" | head -n -1  | shuf -n 1`; echo $RAND_ENV | cut -d " " -f3 | cowsay; eval $RAND_ENV'
    dest: "{{ home }}/.bashrc"
