---

- name: install git
  become_user: root
  pacman:
    name: git
    state: latest

- name: set git email
  git_config:
    name: user.email
    value: "{{ email }}"
    scope: global

- name: set git name
  git_config:
    name: user.name
    value: "{{ fullname }}"
    scope: global
