---

- name: install/update gnome-terminal
  become_user: root
  apt:
    name: gnome-terminal
    state: latest

- name: install dconf-cli
  become_user: root
  apt:
    name: dconf-cli
    state: latest

- name: download monokai theme for gnome-terminal
  become_user: root
  git:
    repo: https://github.com/pricco/gnome-terminal-colors-monokai.git
    dest: /opt/gnome-terminal-colors-monokai

- name: install monokai theme for gnome-terminal
  shell: "bash install.sh -p ':b1dcc9dd-5262-4d8d-a863-c897e6d979b9'"
  args:
    chdir: /opt/gnome-terminal-colors-monokai
    creates: /opt/gnome-terminal-colors-monokai/is_installed

- name: remove transparency
  shell: "dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency false"
  args:
    creates: /opt/gnome-terminal-colors-monokai/is_installed
    
- name: monokai gnome-terminal sentinel 
  become_user: root
  file:
    path: /opt/gnome-terminal-colors-monokai/is_installed
    state: link
    src: /dev/null
