---

- name: install htop
  become_user: root
  pacman:
    name: htop
    state: latest

- name: install tree
  become_user: root
  pacman:
    name: tree
    state: latest

- name: alias tree to tree -C
  lineinfile:
    line: alias tree="tree -C"
    dest: "{{ bashrc }}"

- name: alias uuid
  lineinfile:
    line: alias uuid='python -c "import uuid; print(uuid.uuid4())"'
    dest: "{{ bashrc }}"

- name: install xclip
  become_user: root
  pacman:
    name: xclip
    state: latest

- name: install cowsay
  become_user: root
  pacman:
    name: cowsay
    state: latest

- name: no ansible cows
  become_user: root
  lineinfile:
    line: nocows = 1
    dest: /etc/ansible/ansible.cfg
    insertafter: ^\[defaults\]$

- name: install fortune
  become_user: root
  pacman:
    name: fortune-mod
    state: latest

- name: install lolcat
  become_user: root
  pacman:
    name: lolcat
    state: latest

- name: install ascii
  become_user: root
  pacman:
    name: ascii
    state: latest

- name: install espeak
  become_user: root
  pacman:
    name: espeak
    state: latest

- name: install jq
  become_user: root
  pacman:
    name: jq

- name: install cmus
  become_user: root
  pacman:
    name: cmus
    state: latest
