---

- name: install neovim
  become_user: root
  pacman:
    name: neovim
    state: latest

- name: alias nvim to vi/vim
  lineinfile:
    line: "alias {{ item }}=nvim"
    dest: "{{ home }}/.bashrc"
  with_items:
    - vi
    - vim

- name: set default editor
  lineinfile:
    line: "export EDITOR=nvim"
    dest: "{{ home }}/.bashrc"
