---

- name: create autoload dir in neovim config
  file:
    path: "{{ home }}/.config/nvim/autoload"
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.config/nvim/autoload/plug.vim"

- name: skeleton init.vim
  copy:
    src: init.skel.vim
    dest: "{{ vimrc }}"
    backup: yes
    force: no
